### ISSUE TITLE
File Upload Questions Not Saving or Allowing Progress in Application

### ISSUE THREAD

**Issue by ldinhcos** [civiform/civiform#10444]
**Describe the bug**
File upload questions are not saving the uploaded files and prevent me from continuing the application. An error message appears when these questions are marked as required.

**To Reproduce**

1. Navigate to any application (in this case, I used the EDRA app).
2. Locate a question that requires a file upload.
3. Upload a file.
4. Click “Continue.

**Expected behavior**
I expect the uploaded files to be saved and to be able to proceed with the application without errors.

**Screenshots**

![Image](https://github.com/user-attachments/assets/9bafa721-9689-4a14-ae25-c709720bf7d0)

**Desktop (please complete the following information):**

- MacOS
- Chrome
- Version 135.0.7049.85 (Official Build) (arm64)

**Additional context**

**Comment by ldinhcos** [comment]
I’m currently seeing this issue in our test environment for the following applications I’ve tried: the Home Repair Loan Program and the Economic Displacement Relocation Assistance (EDRA) Program.

One thing to note is that the EDRA application’s visibility is set to hidden. You can check the link here: https://civiformtest.seattle.gov/programs/edra

I'm also attaching a screencast to show you what I am observing:

https://github.com/user-attachments/assets/99629d07-ed21-4114-bb32-206a9af3c274

**Comment by swatkat1** [comment]
Feature is working fine in Staging but doesn't work on Testing site. There is nothing in the logs to indicate its an error- 

![Image](https://github.com/user-attachments/assets/8ee6eac0-b145-45e4-bcec-197ed25dcc38)

**Comment by swatkat1** [comment]
this is the issue-

```
Uncaught Error: Modal Container display not found!
    at new e (modal.ts:76:13)
    at Object.init (modal.ts:105:3)
    at applicant_entry_point.ts:38:9

```
![Image](https://github.com/user-attachments/assets/edf6d8b1-81eb-4812-81b6-e5834a06a746)

**Comment by dkatzz** [comment]
Thanks for noticing that, @swatkat1 ! Could you let me know if you still see this after deploying? And do you have any experimental flags on aside from northstar enabled? Because modals don't work, I can't click on devtools

**Comment by dkatzz** [comment]
Realized this is an issue from another setting - planning to fix it for this release

**Comment by dkatzz** [comment]
This should be fixed in the latest release

**Comment by swatkat1** [comment]
This is still failing after the latest release. @dkatzz - I don't know if have capacity to pick up. But I will open the issue to track it.
