### ISSUE TITLE
Status name overflows the 'default status' banner

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#5000]
**Describe the bug**
Given that there seem to be no length limitation on application status names, very long names overflow the 'application submitted' banner.

**To Reproduce**

1. As a CiviForm admin, go to the Programs tab.
2. Find a draft program (or create one if needed).
3. Click on the three dots menu to the right and select "Manage application statuses."
4. Click on the "Create a new status" button.
5. Give your new status a very long name.
6. Select the "Set as default status" checkbox.
7. Click the "Confirm" button.
8. Click "OK" on the "The default status will be updated to..." popup.
9. See the green banner which says:  "<status name> has been updated to the default status."  Notice that the text overflows the banner.

**Expected behavior**
I expect the application status name to fit within the bounds of the banner.  If we want to allow for longer names (not sure why we would need such long names), we could truncate them within the banner.

**Screenshots**
![image](https://github.com/civiform/civiform/assets/134556723/af06f36d-de1d-4384-9bc6-97a6237e5939)

**Desktop (please complete the following information):**

- OS: iOS
- Browser: Chrome
- Version: 113.0.5672.126

**Smartphone (please complete the following information):**

Did not verify bug on mobile.

**Additional context**
As a technical note, I would suggest adding a length limit on the status name input field.  Apart from fixing this particular bug, it would prevent other such bugs from occurring.

**Comment by mepps** [comment]
@melanie-exygy Similar to #5001 this only occurs with an unbroken block of text. Another place where I agree a character limit is needed though. I don't think anyone wants a status like this :).
<img width="1468" alt="Screenshot 2023-06-02 at 2 00 04 PM" src="https://github.com/civiform/civiform/assets/4406809/b5282696-08bb-4a49-8641-9af0e1f827cd">

**Comment by azhangggggg** [comment]
Consulted ppl in prox-management since it's more of a product question -  it seems like we're on board with limiting status to 35 characters. I will add this limit to the PR.

**Comment by gwendolyngoetz** [comment]
Seattle has multiple entries that are greater than this limit. 

Instead of limiting the character count we could wrap or truncate the text in the banner since it's just a UI issue.

**Comment by azhangggggg** [comment]
> Seattle has multiple entries that are greater than this limit.
> 
> Instead of limiting the character count we could wrap or truncate the text in the banner since it's just a UI issue.

No problem. I can fix this soon.

**Comment by ssandbekkhaug** [comment]
Looks like this is fixed. Can this issue be closed?

<img width="1422" alt="Screenshot 2024-05-21 at 9 29 31 AM" src="https://github.com/civiform/civiform/assets/23390490/90a88019-7d9c-49ea-8421-f8766e239165">

**Comment by gwendolyngoetz** [comment]
How's it look with a long string that has no spaces to naturally break on?

**Comment by melanie-exygy** [comment]
> Looks like this is fixed. Can this issue be closed?
> 
> <img alt="Screenshot 2024-05-21 at 9 29 31 AM" width="1422" src="https://private-user-images.githubusercontent.com/23390490/332465277-90a88019-7d9c-49ea-8421-f8766e239165.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3ODM1NjksIm5iZiI6MTcyNjc4MzI2OSwicGF0aCI6Ii8yMzM5MDQ5MC8zMzI0NjUyNzctOTBhODgwMTktN2Q5Yy00OWVhLTg0MjEtZjg3NjZlMjM5MTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDIyMDEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMGMyMTNjODI1MDMxNDAzOWI2OWRiZGExZWMwYjAyMmQwY2NkMmIzNGZiNGQ5NjE3NWY0ZGNiOGE2ZTA5ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IzL3OwTCXSpenTt6EJQQL3C3ZgILA7Nup4RcYm1C97s">

The issue is still present.  The status needs to be a long string without spaces.

![image](https://github.com/user-attachments/assets/3e88b7e7-b169-4331-bd2e-30d479bbe7b5)
