### ISSUE TITLE
[North Star Applicant UI] Header is too short on mobile

### ISSUE THREAD

**Issue by greg-hyde** [civiform/civiform#7895]
Default USWDS styles make the header 48 pixels high, but that's smaller than the civiform test logo and the city of seattle logo, making the logo overflow, so we should update that default height

![6UHvVRCXZUdsxM7](https://github.com/civiform/civiform/assets/156004543/cf5721f4-9af8-41ef-a2f5-292bc81227d6)

**Comment by sijiayam** [comment]
We should resize the logo to fit into the header.

**Comment by ssandbekkhaug** [comment]
Latest mocks from Sijia: https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=1832-691&t=wy3cHG9jLQyOHV2y-0

**Comment by ssandbekkhaug** [comment]
Fixed by #7961

**Comment by sijiayam** [comment]
Testing is blocked by #9035

**Comment by sijiayam** [comment]
I am still seeing this issue on staging on screen sizes <1024px. See image attached below. I am going to reopen issue until it is resolved. 
![Image](https://github.com/user-attachments/assets/d4355798-7b5a-4ee9-a32b-48d0d748368c)

**Comment by ssandbekkhaug** [comment]
Oh, that's because PR#7961 did not update the PNG used by staging: https://github.com/civiform/civiform-staging-assets/blob/main/logos/civiform-staging.png

**Comment by ssandbekkhaug** [comment]
https://github.com/civiform/civiform-staging-assets/pull/4

**Comment by ssandbekkhaug** [comment]
Open questions:

1. What should the "correct" dimensions of the logo be?
2. If the government provides a differently-sized logo, what should happen? (Too large or too small, very wide, very tall, etc)

**Comment by sijiayam** [comment]
- Logo should have a height of 64px and max-height of 64px
- If logo height exceeds 64px, logo should be resized to fit
- If logo height is under 64px, logo should be icreased to fit

**Comment by shreyachatterjee00** [comment]
@sijiayam is this still an issue? I'm seeing this on the same px size you tried - the logo isn't cutoff at the top

<img width="1012" alt="Image" src="https://github.com/user-attachments/assets/91d82d93-c9fb-4afa-87aa-bd53d836d384" />

**Comment by sijiayam** [comment]
I'm still seeing it at specific breakpoints. Maybe its a tablet screen issue

<img width="959" alt="Image" src="https://github.com/user-attachments/assets/4124c216-5f0a-46b7-bf39-3de85298c3df" />

**Comment by shreyachatterjee00** [comment]
oh nevermind, I see it now. Going to delete my comment so it doesn't clutter the issue

**Comment by watermandrewc** [comment]
The USWDS header height on mobile is 48px. @sijiayam do we want to increase the height of the header and the menu button to 64px?

Also I don't see the logo in the header on mobile in the mocks linked -- do we still want to display the logo on mobile?

**Comment by sijiayam** [comment]
@watermandrewc Lets remove the logo on mobile and tablet. I think that should solve the issue. https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=1836-7143
